### ISSUE TITLE
Can't display comparator listing when some domains have no similarity data

### ISSUE THREAD

**Issue by jmb01** [OHDSI/ComparatorSelectionExplorer#4]
When testing on new data sources, it appears that occasionally one will have no information on a specific covariate domain (e.g., visit context). This leads to an error when `pivot_wider()` is called [here](https://github.com/OHDSI/ComparatorSelectionExplorer/blob/4600a3c7dc27ba0db4eff6f52481cd8a1f7f810a/inst/shiny/server.R#L228). 

This error occurred when selecting target database: Optum EHR, target exposure: ocrelizumab.

**Comment by azimov** [comment]
@jmb01  i think this was fixed in the latest release?

**Comment by jmb01** [comment]
> @jmb01 i think this was fixed in the latest release?

Yes, closing the issue now.
